routes/web.php
<?php

use App\Http\Controllers\CrController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MessagesController;
use App\Http\Controllers\OrdreController;
use App\Http\Controllers\StatsController;
use App\Livewire\Arbitre\Dashboard;
use App\Livewire\OrdresRendus;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::redirect('/', '/home');
Route::get('/home', [HomeController::class, 'index']);
Route::get('/stats/ordresrendus', OrdresRendus::class);
Route::get('/stats/rumeurs', [StatsController::class, 'rumeurs']);
Route::get('/stats/messages', [StatsController::class, 'messages']);

Route::middleware('auth')->group(function () {
    Route::get('/confpref', \App\Livewire\PreferencesForm::class)->name('confpref');
    Route::get('/ordres/{user?}', [OrdreController::class, 'edit'])->name('ordres')
        ->where(['user' => '[A-Z0-9]+\-[0-9]+']);
    Route::post('/ordres/{user}', [OrdreController::class, 'update'])
        ->where(['user' => '[A-Z0-9]+\-[0-9]+']);
    Route::get('/crtexte/{user?}', [CrController::class, 'crTexte'])->name('crtexte');
    Route::get('/cr', [CrController::class, 'crZip'])->name('cr');
    Route::get('/plan', [CrController::class, 'plan'])->name('plan');
    Route::get('/plan/{user}', [CrController::class, 'plan'])->name('arbitre.plan')
        ->where(['user' => '[A-Z0-9]+\-[0-9]+'])
        ->middleware('arbitre');
    Route::get('/plan', [CrController::class, 'plan'])->name('plan');
    Route::get('/nebutil', [CrController::class, 'nebutil'])->name('nebutil');
    Route::get('/nebutil/{user}', [CrController::class, 'nebutil'])->name('arbitre.nebutil')
        ->where(['user' => '[A-Z0-9]+\-[0-9]+'])
        ->middleware('arbitre');
});

Route::redirect('/arbitre', '/arbitre/dashboard');
Route::group(['prefix' => 'arbitre', 'middleware' => ['auth', 'arbitre']], function() {
    Route::get('/dashboard', Dashboard::class)->name('arbitre.dashboard');
    Route::get('/crnba', [CrController::class, 'crNba'])->name('crnba');
});

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', [MessagesController::class, 'index'])->name('messages');
    Route::get('create/{typeMessage?}', [MessagesController::class, 'create'])
        ->name('messages.create')
        ->where(['typeMessage' => 'message|mg|rumeur']);
    Route::post('/', [MessagesController::class, 'store'])->name('messages.store');
    Route::get('{id}', [MessagesController::class, 'show'])->name('messages.show');
    Route::put('{id}', [MessagesController::class, 'update'])->name('messages.update');
});

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use App\Notifications\MessageNotification;
use App\Models\User;
use Arr;
use Cache;
use Carbon\Carbon;
use Cmgmyr\Messenger\Models\Message;
use Cmgmyr\Messenger\Models\Participant;
use Cmgmyr\Messenger\Models\Thread;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Validation\Rule;
use Notification;
use Gate;

/**
 * Class MessagesController
 * @package App\Http\Controllers
 */
class MessagesController extends Controller
{

    /**
     * MessagesController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show all of the message threads to the user.
     * TODO à supprimer car réécrit avec Livewire
     *
     * @return mixed
     */
    public function index()
    {
        return view('messenger.index');
    }

    /**
     * Shows a message thread.
     * TODO à supprimer lorsque MessageShow sera SPA
     * @param $id
     * @return mixed
     */
    public function show($id)
    {
        // TODO : essayer de supprimer ce code. Pour le moment un bug livewire empêche ces tests d'y fonctionner
        try {
            $thread = Thread::withCount('participants')->with(['participants.user', 'messages.user'])->findOrFail($id);

        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'Le fil de discussion numéro ' . $id . ' est introuvable.');

            return redirect()->route('messages');
        }

        try {
            $this->authorize('view', $thread);
        } catch (AuthorizationException $e) {
            Session::flash('error_message', $e->getMessage());

            return redirect()->route('messages');
        }

        // don't show the current user in list
        $user_id = Auth::id();
        // $users = Auth::user()->partie->joueur->whereNotIn('id', $thread->participantsUserIds($user_id));

        return view('messenger.show', compact('user_id', 'thread'));
    }

    /**
     * Génère la liste des joueurs connus de noms et coéquipiers
     * @return User[]|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    private function getJoueursData()
    {
        if (Auth::user()->isArbitre())
            return Auth::user()->partie->joueurs_sans_arbitre->get();
        else {
            $relations = collect()
                ->push(Auth::user()->partie->arbitre)
                ->merge(isset(Auth::user()->equipe) ? Auth::user()->coequipiers()->get() : null)
                ->merge(Auth::user()->partie->diplomatie ? Auth::user()->relations()->get() : null)
                ->where('id', '<>', Auth::user()->id)
                ->unique('id');

            return $relations->sortBy('numjou');
        }
    }
    /**
     * Creates a new message thread.
     *
     * @return mixed
     */
    public function create($typeMessage = 'message')
    {
        $this->authorize('create', Thread::class);
        if ($typeMessage == 'mg') {
             Gate::authorize('msg_general');
        }

        if ($typeMessage === '') {
            $typeMessage = 'message';
        }

        // On regarde si un destinataire est fourni en paramètre
        $dest = null;
        if (request()->input('dest')) {
            // $dest est un numéro de joueur
            if (Auth::user()->partie->joueur->where('numjou', request()->input('dest'))->count() == 1) {
                $dest = (int) request()->input('dest');
            };
        }

        $users = $this->getJoueursData();
        $diplomatie = Auth::user()->partie->diplomatie;

        // Initialisation objet
        if (empty(request()->input('subject', old('subject')))) {
            request()->merge(["subject" => 'Message de ' . Auth::user()->pseudoWithNumJou]);
        }

        return view('messenger.create', compact('users', 'typeMessage', 'dest', 'diplomatie'));
    }

    /**
     * Stores a new message thread.
     *
     * @param Request $request
     * @param User $user
     * @return mixed
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('create', Thread::class);

        $user = Auth::user();

        $request->validate(['type_message' => 'in:message,mg,rumeur']);

        $typeMessage = $request->input('type_message');

        if ($typeMessage === 'message') {
            //$array = $user->relationsId(true);
            $joueursConnusEtCoequipiers = $this->getJoueursData()->pluck('id');

            // On ajoute les clés du tableau recipients en valeur pour la validation qui va suivre
            $recipients = $request->input('recipients');

            if (isset($recipients)) {
                $keys = array_keys($recipients);
                foreach($keys as $key) {
                    $recipients[$key] = $key;
                }
                $request->merge([
                    "recipients" => $recipients
                ]);
            }

            $request->validate([
                'recipients' => 'required',
                'subject' => 'required',
                'message' => 'required',
                'recipients.*' => Rule::in($joueursConnusEtCoequipiers)
            ]);
        } else {
            $request->validate([
                    'message' => 'required',
            ]);
        }

        $input = $request->all();
        $subject = '';

        switch ($typeMessage) {
            case 'message':
                $subject = $input['subject'];
                break;
            case 'mg':
                $subject = "Message général de " . $user->pseudoWithNumJou;
                break;
            case 'rumeur':
                $subject = "RUMEUR";
                break;
        }

        $broadcast = (($typeMessage === 'rumeur') || ($typeMessage === 'mg'));
        $thread = Thread::create([
            'subject' => $subject,
            'anonymous' => ($typeMessage === 'rumeur'),
            'broadcast' => $broadcast,
        ]);

        // Message
        $message = Message::create([
            'thread_id' => $thread->id,
            'user_id' => Auth::id(),
            'body' => $input['message'],
        ]);

        // Sender
        Participant::create([
            'thread_id' => $thread->id,
            'user_id' => Auth::id(),
            'last_read' => new Carbon,
        ]);

        // Recipients
        if ($broadcast) {
            $thread->addParticipant(Arr::pluck($user->partie->joueur, 'id'));
        }
        elseif ($request->has('recipients')) {
            $thread->addParticipant($input['recipients']);
        }

        $thread->updateUnreadMessageCountCache();

        $this->notify($message);

        return redirect()->route('messages');
    }

    private function notify(Message $message)
    {
        // Notification des destinataires
        $recipients = $message->recipients();
        $users = $recipients->get()->map(fn($recipient) => $recipient->user);

        // Si le joueur a demandé de recevoir une copie des messages envoyés sous forme de notification
        if (Auth::user()->cc) {
            $users->push(Auth::user());
        }

        if ($message->thread->isMessageGeneral()) {
            // Filtrage joueurs ne désirant pas recevoir de notification pour les messages généraux
            $users = $users->where('msg_gen', true);
        }

        if ($message->thread->isRumeur()) {
            // Filtrage joueurs ne désirant pas recevoir de notification pour les rumeurs
            $users = $users->where('rumeurs', true);
        }

        Notification::send($users, new MessageNotification($message, false));

        // Notification de l'arbitre
        $hasArbitre = $message->participants()->where('user_id', '=', Auth::user()->partie->arbitre->id)->exists();
        if (Auth::user()->partie->arbitre->cc && (! $hasArbitre)) {
            Notification::send(Auth::user()->partie->arbitre, new MessageNotification($message, true));
        }
    }

    /**
     * Adds a new message to a current thread.
     *
     * @param Request $request
     * @param $id
     * @return mixed
     */
    public function update(Request $request, $id)
    {
        try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'La discussion ' . $id . ' n\' pas été trouvée.');

            return redirect()->route('messages');
        }

        try {
            $this->authorize('update', $thread);
        } catch (AuthorizationException $e) {
            Session::flash('error_message', $e->getMessage());

            return redirect()->route('messages');
        }

        $thread->activateAllParticipants();

        // Message
        $message = Message::create([
            'thread_id' => $thread->id,
            'user_id' => Auth::id(),
            'body' => $request->input('message'),
        ]);

        // Add replier as a participant
        $participant = Participant::firstOrCreate([
            'thread_id' => $thread->id,
            'user_id' => Auth::id(),
        ]);
        $participant->last_read = new Carbon;
        $participant->save();

        // Recipients
        if ($request->has('recipients')) {
            $thread->addParticipant($request->input('recipients'));
        }

        $this->supprimeFlagIgnoreNonrepondus($thread);

        $thread->updateUnreadMessageCountCache();

        $this->notify($message);

        return redirect()->route('messages.show', $id)->withFragment('latest');
    }

    public function supprimeFlagIgnoreNonrepondus(Thread $thread) {
        Participant::whereBelongsTo($thread)->update(['ignore_non_repondu' => false]);
    }
}

app/Livewire/Arbitre/NotificationsConfig.php
<?php

namespace App\Livewire\Arbitre;

use App\Jobs\CallSlack;
use App\Services\Utils;
use Livewire\Component;
use Illuminate\Support\Facades\Auth;

class NotificationsConfig extends Component
{

    public string $testTexte = "";
    public string $webhook_ordres_rendus = "";
    public string $webhook_bot = "";
    public $partie;

    protected $rules = [
        'webhook_ordres_rendus' => 'url',
        'webhook_bot' => 'url',
    ];

    public function mount()
    {
        $this->partie = Auth::user()->partie;
        $this->readHooksFromPartie();
    }

    public function render()
    {
        return view('livewire.arbitre.notifications-config');
    }

    public function readHooksFromPartie()
    {
        $this->webhook_ordres_rendus = $this->partie->webhook_ordres_rendus ?? config('nebmail.slack_webhook_url');
        $this->webhook_bot = $this->partie->discord_url ?? config('nebmail.discord_webhook_url');
    }

    public function notificationsFormSubmit()
    {
        $this->validate();
        $this->partie->webhook_ordres_rendus = $this->webhook_ordres_rendus;
        $this->partie->discord_url = $this->webhook_bot;
        $this->partie->save();
    }

    public function testBot()
    {
        $texte = $this->testTexte;
        if (empty($texte)) {
            $texte = 'Test bot';
        }

        Utils::postToDiscord($texte, $this->webhook_bot);
    }

    public function testNotificationMessage()
    {
        $texte = $this->testTexte;
        if (empty($texte)) {
            $texte = 'Test notification ordres rendus';
        }

        CallSlack::dispatch(message: $texte, url: $this->webhook_ordres_rendus);
    }

    public function notificationReset()
    {
        $this->reset('testTexte');
        $this->readHooksFromPartie();
    }
}

app/Livewire/CoordonneesMondes.php
<?php

namespace App\Livewire;

use App\Models\User;
use Livewire\Component;
use App\Models\Coordonnees;
use Illuminate\Support\Facades\Log;
use App\Rules\CoordonneesMondesRule;
use App\Services\CoordonneesService;
use Illuminate\Support\Facades\Auth;

class CoordonneesMondes extends Component
{
    public string $coordonneesTexte;
    public User $user;

    protected $rules = [
        'coordonneesTexte' => ['string']
    ];

    protected $listeners = ['storeCoordonneesFromPlan'];

    public function mount()
    {
        $this->user = Auth::user();
        $this->readUserCoordinates();
    }

    private function readUserCoordinates()
    {
        $this->coordonneesTexte = $this->user->coordonnees?->value ?? '';
    }

    public function render()
    {
        return view('livewire.coordonnees-mondes');
    }

    public function save()
    {
        $this->validate([
            'coordonneesTexte' => ['string', new CoordonneesMondesRule],
        ]);

        $this->user->coordonnees()->updateOrCreate([], ['value' => $this->coordonneesTexte]);
        $coordonneesArray = (new CoordonneesService($this->coordonneesTexte))->mondesAsKeys()->toArray();
        $this->dispatch('coordonnes-updated', coord: $coordonneesArray);
    }

    public function storeCoordonneesFromPlan(array $coordonneesArray)
    {
        $customCoord = (new CoordonneesService($this->user->coordonnees?->value))
            ->mondesAsKeys()
            ->mergeArrayFromJS($coordonneesArray)
            ->coordonneesAsString();

        Coordonnees::updateOrCreate(['user_id' => $this->user->id], ['value' => $customCoord]);

        $this->user->refresh();
        $this->readUserCoordinates();

        $this->dispatch('disable-save-button');

        $this->dispatch('notify',
            typeMsg: 'success',
            msg: 'Coordonnées enregistrées'
        );
    }
}

app/Livewire/Crtexte.php
<?php

namespace App\Livewire;

use Livewire\Component;

class Crtexte extends Component
{
    public string $crtxt;

    public function render()
    {
        return view('livewire.crtexte');
    }

}

app/Livewire/OrdresRendus.php
<?php

namespace App\Livewire;

use App\Models\Partie;
use Livewire\Component;

class OrdresRendus extends Component
{
    public array $ordres;

    protected $listeners = [
        'echo:ordres.rendus,OrdresRendus' => 'eventOrdresRendus',
        'echo:nouveau.tour,NouveauTour' => 'eventNouveauTour',
    ];

    public function mount()
    {
        $this->ordres = Partie::withCount('ordre')->pluck('ordre_count', 'name')->toArray();

    }

    public function render()
    {
        return view('livewire.ordres-rendus');
    }

    public function eventOrdresRendus($event)
    {
        $this->ordres[$event['partie_name']] = $event['nb_ordres'];
    }

    public function eventNouveauTour($event)
    {
        $this->ordres[$event['partie_name']] = 0;
    }
}

resources/views/livewire/coordonnees-mondes.blade.php
<x-modal
    id="coordonnees-modal"
    title="Coordonnées des mondes"
    :centered="true"
    :scrollable="false"
    size="lg"
    wire:ignore.self
    >
    <form wire:submit="save">
        @csrf
        <x-slot name="body">
            <p>Saisissez l'ensemble des coordonnées de vos mondes, 1 monde par ligne, sous la forme <code>m=x,y</code>. Où m est le numéro du monde concerné et x,y ses coordonnées. Exemple :</p>
            <p><code>5=10,15<br>25=11,3</code></p>
            <p>
                Ces coordonnées vont remplacer celles incluses dans le fichier .nbt stocké sur le serveur.
                Il faut rentrer dans ce champ de saisie l'intégralité des coordonnées que vous voulez voir remplacer,
                y compris celles que vous auriez déjà saisi au prélable.
            </p>
            <div class="form-group">
                <label for="message-text" class="col-form-label">Coordonnées :</label>
                <textarea rows="10" class="form-control" wire:model="coordonneesTexte"></textarea>
                @error('coordonneesTexte') <span class="text-danger">{{ $message }}</span> @enderror
            </div>
        </x-slot>
        <x-slot name="footer">
            <button type="button" class="btn btn-success" wire:click="save" id="coordonnees-save-button">Envoyer</button>
            <button type="button" class="btn btn-warning" data-dismiss="modal">Annuler</button>
        </x-slot>
</form>
</x-modal>

@push('page-js-script')
<script type="module">
    window.addEventListener('coordonnes-updated', event => {
        $("#coordonnees-modal").modal('hide')
    })

    document.addEventListener('disable-save-button', event => {
        document.querySelector("#coordonnees-save-button").disabled = false;
    })

    document.addEventListener('enable-save-button', event => {
        document.querySelector("#coordonnees-save-button").disabled = true;
    })
</script>
@endpush

resources/views/livewire/crtexte.blade.php
<div id="nebutil-cr" wire:ignore>
    <form>
        <div class="form-group">
            <textarea id="crtexte" rows="20" class="form-control CodeMirror">{{ $crtxt ?? '' }}</textarea>
        </div>
    </form>
</div>

@push('page-js-files')
@vite(['resources/js/ordres/codemirror.js'])
@endpush

@push('page-js-script')
<script type="module">
    let textAreaCr = document.getElementById('crtexte');
    if (textAreaCr != null) {
        var myCodeMirrorCr = CodeMirror.fromTextArea(textAreaCr, {
            lineNumbers: false,
            mode:  null,
            dragDrop: false,
            autofocus: true,
        });
    }
    else {
        alert('myTextarea est null');
    }

    window.addEventListener('dessine-plan', event => {
        if (myCodeMirrorCr) {
            const divcr = document.querySelector('#nebutil-cr')

            if (event.detail.simul) {
                divcr.classList.add('cr-simul')
            } else {
                divcr.classList.remove('cr-simul')
            }

            if (event.detail.ancientour) {
                divcr.classList.add('cr-tour-prec')
            } else {
                divcr.classList.remove('cr-tour-prec')
            }

            myCodeMirrorCr.doc.setValue(event.detail.crtxt);
        }
    })

    window.addEventListener('selection-monde', event => {
        if (!event.detail.from === 'cr') {
            return;
        }

        const num_monde = event.detail.monde
        let doc = myCodeMirrorCr.doc

        let num_ligne = getNumLigneFromNumMonde(num_monde)
        if (num_ligne) {
            if (--num_ligne < 0) {
                num_ligne = 0
            }

            doc.setCursor(doc.lineCount() - 1, 0, {scroll: true})
            doc.setCursor(num_ligne, 0, {scroll: true})
        }

    })

    function getNumLigneFromNumMonde(num_monde) {
        let doc = myCodeMirrorCr.doc
        let regexp = new RegExp('^Md?[#_]?' + num_monde + '\\s', '');
        for (let num_ligne = 0; num_ligne < doc.lineCount(); num_ligne++) {
            let ligne = doc.getLine(num_ligne)
            if (ligne.match(regexp)) {
                return num_ligne
            }
        }

        return null
    }



</script>
@endpush

resources/views/livewire/edition-ordres.blade.php
<div x-data="ordres" class="pt-2">
    <form wire:ignore>
        <div class="form-group">
            <textarea class="form-control CodeMirror" rows="20" spellcheck="false"
                name="ordres" id="ordres"></textarea>
        </div>
    </form>
    <div class="d-flex">
        <button id="envoi_button" name="envoi" x-on:click="envoi()" class="mr-2 btn btn-sm btn-primary">Envoyer mes
            ordres</button>
        <button id="brouillon_button" name="brouillon" x-on:click="brouillon()" class="mr-2 btn btn-sm btn-primary">Enregistrer
            le brouillon</button>
        <button id="simul_button" name="simul" x-on:click="simul()" class="mr-2 btn btn-sm btn-primary">Simulation
            d'évaluation</button>
        <button id="sortie_simul_button" x-cloak x-show="simul_eval" name="sortie_simul" x-on:click="sortieSimul()"
            class="mx-2 btn btn-sm btn-success">Revenir au CR d'origine</button>
        <button x-text="statuts[ordres_statut]"
            x-bind:class="{
                'btn-success': ordres_statut == 'sent',
                'btn-warning': ordres_statut == 'draft',
                'btn-danger': ordres_statut == 'changed'
            }"
            disabled
            id="ordres_statut"
            class="ml-auto btn btn-sm"></button>
    </div>
</div>

@push('page-js-script')
    @vite(['resources/js/ordres/ordres.mjs'])
    <script type="module">
        document.addEventListener('alpine:init', () => {
            Alpine.data('ordres', () => ({
                simul_eval: false,
                ordres_statut: "{{ $this->brouillon ? 'draft' : 'sent'}}",
                original_ordres_statut: '',
                statuts: {
                    sent: 'Envoyé',
                    draft: 'Brouillon',
                    changed: 'Non enregistré'
                },
                editionOrdres: null,

                init() {
                    Ordres.alpineInit(this, @this)
                },

                envoi() {
                    Ordres.envoi(this, @this)
                },

                brouillon() {
                    Ordres.brouillon(this, @this)
                },

                simul() {
                    Ordres.simul(this, @this)
                },

                sortieSimul() {
                    Ordres.sortieSimul(this)
                }
            }))
        })
    </script>
@endpush

resources/views/livewire/message-show.blade.php
<div class="container">
    <div class="col">
        <h3 class="mb-3">{{ $thread->subject }}</h3>

        <div>
        @if ($thread->participants_count > 2)
            <div class="alert alert-warning">Discussion à plusieurs avec {{ $thread->participantsString($user->id) }}</div>
        @endif
        </div>

        @foreach($thread->messages as $message)
        @php
            $class = $message->user->id != $user->id ? 'ml-5 bg-info' : 'mr-5'
        @endphp
        <div class="card mb-2 {{ $class }}" @if($loop->last) id="latest" @endif>
            <div class="card-header">
                @if (!$thread->anonymous)De : {{ $message->user->pseudoWithNumJou }}@else Une rumeur court en ce moment @endif <small>{{ $message->created_at->diffForHumans() }}</small>
                @if($loop->count > 1 && $loop->first) <a href="#latest"><iconify-icon icon="ic:vertical-align-bottom" class='mr-1 md-24 float-right' title='Aller en bas de la page'></iconify-icon></a> @endif
                @if($loop->count > 1 && $loop->last) <a href="#app"><iconify-icon icon="ic:vertical-align-top" class='mr-1 md-24 float-right' title='Aller en haut de la page'></iconify-icon></a> @endif
            </div>
            <div class="card-body">
                <pre style="white-space: pre-wrap; font-size: 90%;">{{ $message->body }}</pre>
            </div>
        </div>
        @endforeach


        <h3 class="mt-3">Répondre à la discussion</h3>
        <form method="post" action="{{ route('messages.update', [$thread->id]) }}">
            @csrf
            @method('PUT')

            <x-textarea
            name="message"
            required
            rows="15"
            class='text-monospace'
            :label="[
                'text' => 'Votre message',
            ]"
            />

            <button type="submit" class="btn btn-primary">Envoyer le message</button>
        </form>

    </div>
</div>

resources/views/livewire/messages-count.blade.php
<span class="messages-count">
    @if ($this->count > 0)
    <span class="badge badge-pill badge-danger">{{ $this->count }}</span>
    @endif
</span>

resources/views/livewire/ordres-rendus-partie.blade.php
<span>
    @if (isset($nbOrdres) && $nbOrdres > 0)
    <span class="badge badge-info">{{ $partieName }} : {{ $nbOrdres }}</span>
    @endif
</span>

resources/views/livewire/ordres-rendus.blade.php
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">Ordres rendus</div>
                <div class="card-body ">
                    <table class="table table-borderless table-sm">
                        <thead>
                            <tr>
                                <th>Partie</th>
                                <th class="text-center">Ordres</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($ordres as $partie => $nbOrdres)
                                <tr>
                                    <td>{{ $partie }}</td>
                                    <td class="text-center">{{ $nbOrdres }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>